// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your api key here', //todo add api key
    appId: '1:261888003913:web:4842673e2620183d9cd498',
    messagingSenderId: '261888003913',
    projectId: 'complaintnow-77739',
    authDomain: 'complaintnow-77739.firebaseapp.com',
    storageBucket: 'complaintnow-77739.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your api key here',//todo add api key
    appId: '1:261888003913:android:d0513da97df477d49cd498',
    messagingSenderId: '261888003913',
    projectId: 'complaintnow-77739',
    storageBucket: 'complaintnow-77739.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your api key here',//todo add api key
    appId: '1:261888003913:ios:98b6475d43cc6a469cd498',
    messagingSenderId: '261888003913',
    projectId: 'complaintnow-77739',
    storageBucket: 'complaintnow-77739.appspot.com',
    iosClientId: '261888003913-oseif2mmn4mkmrd4ng1a434ttm2q5l6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your api key here',//todo add api key
    appId: '1:261888003913:ios:98b6475d43cc6a469cd498',
    messagingSenderId: '261888003913',
    projectId: 'complaintnow-77739',
    storageBucket: 'complaintnow-77739.appspot.com',
    iosClientId: '261888003913-oseif2mmn4mkmrd4ng1a434ttm2q5l6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your api key here',//todo add api key
    appId: '1:261888003913:web:b9c57570e019ef099cd498',
    messagingSenderId: '261888003913',
    projectId: 'complaintnow-77739',
    authDomain: 'complaintnow-77739.firebaseapp.com',
    storageBucket: 'complaintnow-77739.appspot.com',
  );

}